In [1]:
import pandas as pd

In [6]:
df_Sv = pd.read_csv(
    "/home/ctuguinay/echodataflow_test/output/Sv_files.csv",
    index_col=0,
    date_format="ISO8601",
    parse_dates=["first_ping_time", "last_ping_time"]
)
df_Sv

,raw_filename,Sv_filename,first_ping_time,last_ping_time
0,Hake-D20230804-T164148.raw,Hake-D20230804-T164148_Sv.zarr,2023-08-04 16:41:48.307949,2023-08-04 16:46:09.154161
1,Hake-D20230804-T164610.raw,Hake-D20230804-T164610_Sv.zarr,2023-08-04 16:46:10.349979,2023-08-04 16:50:26.749968
2,Hake-D20230804-T165027.raw,Hake-D20230804-T165027_Sv.zarr,2023-08-04 16:50:27.961729,2023-08-04 16:54:51.134266
3,Hake-D20230804-T165452.raw,Hake-D20230804-T165452_Sv.zarr,2023-08-04 16:54:52.355005,2023-08-04 16:59:15.220356
4,Hake-D20230804-T165916.raw,Hake-D20230804-T165916_Sv.zarr,2023-08-04 16:59:16.414165,2023-08-04 17:03:38.062754
5,Hake-D20230804-T170339.raw,Hake-D20230804-T170339_Sv.zarr,2023-08-04 17:03:39.279501,2023-08-04 17:07:57.800514
6,Hake-D20230804-T170758.raw,Hake-D20230804-T170758_Sv.zarr,2023-08-04 17:07:58.991316,2023-08-04 17:12:19.872564
7,Hake-D20230804-T171221.raw,Hake-D20230804-T171221_Sv.zarr,2023-08-04 17:12:21.056383,2023-08-04 17:16:40.626137
8,Hake-D20230804-T171641.raw,Hake-D20230804-T171641_Sv.zarr,2023-08-04 17:16:41.811981,2023-08-04 17:21:01.645643
9,Hake-D20230804-T172102.raw,Hake-D20230804-T172102_Sv.zarr,2023-08-04 17:21:02.862387,2023-08-04 17:25:22.924578
10,Hake-D20230804-T172524.raw,Hake-D20230804-T172524_Sv.zarr,2023-08-04 17:25:24.144314,2023-08-04 17:29:48.684889
11,Hake-D20230804-T172949.raw,Hake-D20230804-T172949_Sv.zarr,2023-08-04 17:29:49.902130,2023-08-04 17:34:44.950945
12,Hake-D20230804-T173446.raw,Hake-D20230804-T173446_Sv.zarr,2023-08-04 17:34:46.492823,2023-08-04 17:40:18.000994
13,Hake-D20230804-T174019.raw,Hake-D20230804-T174019_Sv.zarr,2023-08-04 17:40:19.572792,2023-08-04 17:45:52.363268
14,Hake-D20230804-T174553.raw,Hake-D20230804-T174553_Sv.zarr,2023-08-04 17:45:53.915125,2023-08-04 17:51:31.728239
15,Hake-D20230804-T175133.raw,Hake-D20230804-T175133_Sv.zarr,2023-08-04 17:51:33.271132,2023-08-04 17:58:09.737223
16,Hake-D20230804-T175811.raw,Hake-D20230804-T175811_Sv.zarr,2023-08-04 17:58:11.743858,2023-08-04 18:05:53.087282
17,Hake-D20230804-T180555.raw,Hake-D20230804-T180555_Sv.zarr,2023-08-04 18:05:55.225567,2023-08-04 18:13:08.444262
18,Hake-D20230804-T181310.raw,Hake-D20230804-T181310_Sv.zarr,2023-08-04 18:13:10.649372,2023-08-04 18:21:01.011724
19,Hake-D20230804-T182103.raw,Hake-D20230804-T182103_Sv.zarr,2023-08-04 18:21:03.215837,2023-08-04 18:29:02.296200

In [7]:
df_MVBS = pd.read_csv(
    "/home/ctuguinay/echodataflow_test/output/MVBS_files.csv",
    index_col=0,
    date_format="ISO8601",
    parse_dates=["first_ping_time", "last_ping_time"]
)
df_MVBS

               MVBS_filename     first_ping_time      last_ping_time
0  MVBS_20230804T164000.zarr 2023-08-04 16:41:45 2023-08-04 16:59:55
1  MVBS_20230804T170000.zarr 2023-08-04 17:00:00 2023-08-04 17:19:55
2  MVBS_20230804T172000.zarr 2023-08-04 17:20:00 2023-08-04 17:39:55
3  MVBS_20230804T174000.zarr 2023-08-04 17:40:00 2023-08-04 17:59:55
4  MVBS_20230804T180000.zarr 2023-08-04 18:00:00 2023-08-04 18:19:55
5  MVBS_20230804T182000.zarr 2023-08-04 18:20:00 2023-08-04 18:29:00

In [5]:
df_prediction = pd.read_csv(
    "/home/ctuguinay/echodataflow_test/output/prediction_files.csv",
    index_col=0,
    date_format="ISO8601",
    parse_dates=["first_ping_time", "last_ping_time"]
)
df_prediction

,prediction_filename_postfix,score_filename,softmax_filename,first_ping_time,last_ping_time
0,20230804T164000,score_20230804T164000.zarr,softmax_20230804T164000.zarr,2023-08-04 16:41:45+00:00,2023-08-04 17:19:55+00:00
1,20230804T172000,score_20230804T172000.zarr,softmax_20230804T172000.zarr,2023-08-04 17:20:00+00:00,2023-08-04 17:39:55+00:00
2,20230804T180000,score_20230804T180000.zarr,softmax_20230804T180000.zarr,2023-08-04 18:00:00,2023-08-04 18:19:55

In [9]:
df_MVBS["last_ping_time"]

0   2023-08-04 16:59:55
1   2023-08-04 17:19:55
2   2023-08-04 17:39:55
3   2023-08-04 17:59:55
4   2023-08-04 18:19:55
5   2023-08-04 18:29:00
Name: last_ping_time, dtype: datetime64[us]

In [10]:
import xarray as xr

In [13]:
ds_MVBS = xr.open_zarr("/home/ctuguinay/echodataflow_test/output_20260625/MVBS/MVBS_20230804T182000.zarr",)
ds_MVBS["ping_time"]

<xarray.DataArray 'ping_time' (ping_time: 109)> Size: 872B
array(['2023-08-04T18:20:00.000000000', '2023-08-04T18:20:05.000000000',
       '2023-08-04T18:20:10.000000000', '2023-08-04T18:20:15.000000000',
       '2023-08-04T18:20:20.000000000', '2023-08-04T18:20:25.000000000',
       '2023-08-04T18:20:30.000000000', '2023-08-04T18:20:35.000000000',
       '2023-08-04T18:20:40.000000000', '2023-08-04T18:20:45.000000000',
       '2023-08-04T18:20:50.000000000', '2023-08-04T18:20:55.000000000',
       '2023-08-04T18:21:00.000000000', '2023-08-04T18:21:05.000000000',
       '2023-08-04T18:21:10.000000000', '2023-08-04T18:21:15.000000000',
       '2023-08-04T18:21:20.000000000', '2023-08-04T18:21:25.000000000',
       '2023-08-04T18:21:30.000000000', '2023-08-04T18:21:35.000000000',
       '2023-08-04T18:21:40.000000000', '2023-08-04T18:21:45.000000000',
       '2023-08-04T18:21:50.000000000', '2023-08-04T18:21:55.000000000',
       '2023-08-04T18:22:00.000000000', '2023-08-04T18:22:05.000000000',
       '2023-08-04T18:22:10.000000000', '2023-08-04T18:22:15.000000000',
       '2023-08-04T18:22:20.000000000', '2023-08-04T18:22:25.000000000',
       '2023-08-04T18:22:30.000000000', '2023-08-04T18:22:35.000000000',
       '2023-08-04T18:22:40.000000000', '2023-08-04T18:22:45.000000000',
       '2023-08-04T18:22:50.000000000', '2023-08-04T18:22:55.000000000',
       '2023-08-04T18:23:00.000000000', '2023-08-04T18:23:05.000000000',
       '2023-08-04T18:23:10.000000000', '2023-08-04T18:23:15.000000000',
       '2023-08-04T18:23:20.000000000', '2023-08-04T18:23:25.000000000',
       '2023-08-04T18:23:30.000000000', '2023-08-04T18:23:35.000000000',
       '2023-08-04T18:23:40.000000000', '2023-08-04T18:23:45.000000000',
       '2023-08-04T18:23:50.000000000', '2023-08-04T18:23:55.000000000',
       '2023-08-04T18:24:00.000000000', '2023-08-04T18:24:05.000000000',
       '2023-08-04T18:24:10.000000000', '2023-08-04T18:24:15.000000000',
       '2023-08-04T18:24:20.000000000', '2023-08-04T18:24:25.000000000',
       '2023-08-04T18:24:30.000000000', '2023-08-04T18:24:35.000000000',
       '2023-08-04T18:24:40.000000000', '2023-08-04T18:24:45.000000000',
       '2023-08-04T18:24:50.000000000', '2023-08-04T18:24:55.000000000',
       '2023-08-04T18:25:00.000000000', '2023-08-04T18:25:05.000000000',
       '2023-08-04T18:25:10.000000000', '2023-08-04T18:25:15.000000000',
       '2023-08-04T18:25:20.000000000', '2023-08-04T18:25:25.000000000',
       '2023-08-04T18:25:30.000000000', '2023-08-04T18:25:35.000000000',
       '2023-08-04T18:25:40.000000000', '2023-08-04T18:25:45.000000000',
       '2023-08-04T18:25:50.000000000', '2023-08-04T18:25:55.000000000',
       '2023-08-04T18:26:00.000000000', '2023-08-04T18:26:05.000000000',
       '2023-08-04T18:26:10.000000000', '2023-08-04T18:26:15.000000000',
       '2023-08-04T18:26:20.000000000', '2023-08-04T18:26:25.000000000',
       '2023-08-04T18:26:30.000000000', '2023-08-04T18:26:35.000000000',
       '2023-08-04T18:26:40.000000000', '2023-08-04T18:26:45.000000000',
       '2023-08-04T18:26:50.000000000', '2023-08-04T18:26:55.000000000',
       '2023-08-04T18:27:00.000000000', '2023-08-04T18:27:05.000000000',
       '2023-08-04T18:27:10.000000000', '2023-08-04T18:27:15.000000000',
       '2023-08-04T18:27:20.000000000', '2023-08-04T18:27:25.000000000',
       '2023-08-04T18:27:30.000000000', '2023-08-04T18:27:35.000000000',
       '2023-08-04T18:27:40.000000000', '2023-08-04T18:27:45.000000000',
       '2023-08-04T18:27:50.000000000', '2023-08-04T18:27:55.000000000',
       '2023-08-04T18:28:00.000000000', '2023-08-04T18:28:05.000000000',
       '2023-08-04T18:28:10.000000000', '2023-08-04T18:28:15.000000000',
       '2023-08-04T18:28:20.000000000', '2023-08-04T18:28:25.000000000',
       '2023-08-04T18:28:30.000000000', '2023-08-04T18:28:35.000000000',
       '2023-08-04T18:28:40.000000000', '2023-08-04T18:28:45.000000000',
       '2023-08-04T18:28:50.000000000', '2023-08-04T18:28:55.000000000',
       '2023-08-04T18:29:00.000000000'], dtype='datetime64[ns]')
Coordinates:
  * ping_time  (ping_time) datetime64[ns] 872B 2023-08-04T18:20:00 ... 2023-0...
Attributes:
    long_name:      Ping time
    standard_name:  time
    axis:           T